[package]
name = "rust-chat"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.5"
actix-files = "0.6.6"
actix-web = "4.9.0"
actix-web-actors = "4.3.`"
rand = "0.8.5"
serde = "1.0.214"
serde_json = "1.0.132"